services:
  - type: worker
    name: ai-pomogator
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false   # токен задашь вручную в настройках Render
